name: CD 
on: 
  push: 
    tags: 
      - 'v*.*.*' 
jobs: 
  deploy: 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v3 
    - name: Set up Docker Buildx 
      uses: docker/setup-buildx-action@v2 
    - name: Login to Docker Hub 
      uses: docker/login-action@v2 
      with: 
        username: ${{ secrets.DOCKER_USERNAME }} 
        password: ${{ secrets.DOCKER_PASSWORD }} 
    - name: Build and push Docker image 
      run: 
        docker build -t vignangudla/demo-app:${{ github.ref_name }} . 
        docker push vignangudla/demo-app:${{ github.ref_name }} 
